#!/bin/bash -

readonly tempFile="$(mktemp --tmpdir hashes.XXXXXXXXXXXX)"

function runOnTrap()
{
	rm -rf "$tempFile"
}

function hashDownload()
{
	curl -L "$1" >"$tempFile"
	echo -n MD5:$(md5sum "$tempFile" | awk '{print $1}')
	echo -n ,SHA1:$(sha1sum "$tempFile" | awk '{print $1}')
	echo -n ,SHA256:$(sha256sum "$tempFile" | awk '{print $1}')
	echo ,SHA512:$(sha512sum "$tempFile" | awk '{print $1}')
}

trap runOnTrap 0 HUP INT QUIT ILL ABRT FPE SEGV PIPE TERM EXIT
hashDownload "$1"
runOnTrap
